# Sass Lint Configuration
# See: https://github.com/sasstools/sass-lint

# File Options
files:
  include:
    - "src/sass/*.s+(a|c)ss"
    - "src/sass/**/*.s+(a|c)ss"
    - "src/sass/**/**/*.s+(a|c)ss"
    - "src/sass/**/**/**/*.s+(a|c)ss"
    - "src/components/**/**/*.s+(a|c)ss"
  ignore:
    - "node_modules/**/*.*"

# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false

# Rule Configuration
# See: https://github.com/sasstools/sass-lint/tree/master/docs/rules
rules:
  attribute-quotes:
    - 2
    - include: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  hex-notation:
    - 2
    - style: lowercase
  indentation: 2
  leading-zero:
    - 0
    - include: true
  mixins-before-declarations:
    - 2
    - exclude:
        - breakpoint
        - mq
  nesting-depth:
    - 1
    - max-depth: 3
  no-debug: 1
  no-duplicate-properties: 1
  no-ids: 0
  no-important: 0
  no-trailing-whitespace: 2
  no-vendor-prefixes:
    - 1
    - ignore-non-standard: true
  no-warn: 1
  placeholder-in-extend: 2
  property-sort-order:
    - 1
    - order: "alphabetical"
      ignore-custom-properties: true
  property-units:
    - 1
    - global: ["em", "rem", "vh", "vw", "%"]
  quotes: 2
  single-line-per-selector: 2
  space-after-colon: 2
  space-after-comma: 2
  variable-for-property:
    - 0
    - properties:
        - color
  zero-unit: 2
